[package]
name = "musicbox"
version = "0.1.3"
author = "LifelessRelics <Holozetta@hologramhall.io"
repository = "https://github.com/LifelessRelics/musicbox.git"
description = "Generates a hashmap of musical notes de la musica"
license ="MIT"
edition = "2021"

[[example]]
name="try_lambda"
path="example/try_lambda.rs"
[[example]]
name="use_musicbox"
path="example/use_musicbox.rs"



[dependencies]
